project:
  type: website
  output-dir: docs

website:
  title: "Qui Scribit Bis Legit"
  navbar:
    right:
      - icon: github
        href: https://github.com/iencinas
      - href: test.qmd
        text: testtest

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-fold: true     # Esto permite que el lector oculte/muestre el c칩digo R
    code-copy: true     # A침ade un bot칩n para copiar c칩digo
    toc: true           # Tabla de contenidos a la derecha

editor: visual

